spm:
  - url: 
    from:
    path: 
    branch:
    exact: 
    revision:
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []

ios:
  name: UgProgrammaticUIDev
  id: com.scade.UgProgrammaticUIDev
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  simulator:
    os: 12.1
    output: UgProgrammaticUIDev/.build/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: []
  device: 
    os: 12.1
    output: UgProgrammaticUIDev/.build/ios-device
    extra-args: 
    search-paths: []
    linked-libs: []
  mac:
    os: 10.11
    output: UgProgrammaticUIDev/.build/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs: []
  sign:
    provision-profile:
    certificate:
    beta-reports-active: false
  icons: 
    app-iphone:
      2x:
      3x:
    app-ipad:
      2x:
      3x:
    app-ipad-pro:
      2x:
      3x:
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      type: string
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library

android:
  name: UgProgrammaticUIDev
  id: com.scade.UgProgrammaticUIDev
  version-name: 1.0.0
  version-code: 1
  build-type: Debug
  key-store-properties:
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: UgProgrammaticUIDev/.build/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs: []
  arm64-v8a:
    output: UgProgrammaticUIDev/.build/android-arm64-v8a
    extra-args:
    search-paths: []
    linked-libs: []
  x86:
    output: UgProgrammaticUIDev/.build/android-x86
    extra-args:
    search-paths: []
    linked-libs: []
  x86_64:
    output: UgProgrammaticUIDev/.build/android-x86_64
    extra-args:
    search-paths: []
    linked-libs: []
  intent-filters:
    - action:
      scheme:
      categories: [] 
  icons:
    mdpi:
    hdpi:
    xhdpi: 
    xxhdpi:
