spm:
  - url: git@github.com:stephencelis/SQLite.swift.git
    from: 0.11.0
    path: 
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []

ios:
  name: UgSqlLiteSwift
  id: com.scade.UgSqlLiteSwift
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  simulator:
    os: 12.1
    output: UgSqlLiteSwift/.build/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: [SQLite]
  device: 
    os: 12.1
    output: UgSqlLiteSwift/.build/ios-device
    extra-args: 
    search-paths: []
    linked-libs: [SQLite]
  mac:
    os: 10.11
    output: UgSqlLiteSwift/.build/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs: [SQLite]
  sign:
    provision-profile:
    certificate:
    beta-reports-active: false
  icons: 
    app-iphone:
      2x:
      3x:
    app-ipad:
      2x:
      3x:
    app-ipad-pro:
      2x:
      3x:
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      type: string
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library

android:
  name: UgSqlLiteSwift
  id: com.scade.UgSqlLiteSwift
  version-name: 1.0.0
  version-code: 1
  build-type: Debug
  key-store-properties:
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: UgSqlLiteSwift/.build/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs: [SQLite]
  x86:
    output: UgSqlLiteSwift/.build/android-x86
    extra-args:
    search-paths: []
    linked-libs: [SQLite]
  intent-filters:
    - action:
      scheme:
      categories: [] 
  icons:
    mdpi:
    hdpi:
    xhdpi: 
    xxhdpi:
