spm:
  - url: 
    from:
    path: 
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []

ios:
  name: UgSystemDemo
  id: com.scade.ugsystemdemo
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  simulator:
    os: 12.1
    output: UgSystemDemo/.build/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: []
  device: 
    os: 12.1
    output: UgSystemDemo/.build/ios-device
    extra-args: 
    search-paths: []
    linked-libs: []
  mac:
    os: 10.11
    output: UgSystemDemo/.build/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs: []
  sign:
    provision-profile: /Users/juliawork/ScadeTools/certificates/Scade_Adhoc.mobileprovision
    certificate: /Users/juliawork/ScadeTools/certificates/Certificates.p12
    beta-reports-active: false
  icons: 
    app-iphone:
      2x:
      3x:
    app-ipad:
      2x:
      3x:
    app-ipad-pro:
      2x:
      3x:
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library
  plist: 
    - key: CFBundleURLTypes
      type: list
      values: 
        - type: dict
          values:
            - key: CFBundleURLName
              type: string
              value: com.scade.UgSystemDemo
            - key: CFBundleURLSchemes
              type: list
              values:
                - type: string
                  value: scadedeeplink

android:
  name: UgSystemDemo
  id: com.scade.ugsystemdemo
  version-name: 1.0.0
  version-code: 1
  build-type: Debug
  key-store-properties:
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: UgSystemDemo/.build/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs: []
  x86:
    output: UgSystemDemo/.build/android-x86
    extra-args:
    search-paths: []
    linked-libs: []
  intent-filters:
    - action:
      scheme:
      categories: [] 
  intent-filters:
    - action: android.intent.action.VIEW
      scheme: scadedeeplink
      categories: [android.intent.category.DEFAULT, android.intent.category.BROWSABLE] 
  icons:
    mdpi:
    hdpi:
    xhdpi: 
    xxhdpi:
